# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Fourm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MarkdownView'
  # Pods for Fourm

  target 'FourmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FourmUITests' do
    # Pods for testing
  end

end
